version: "3.2"

services:

  # PostgreSQL for storing task state
  taskdb:
    image: postgres:9.6.2
    environment:
      - "POSTGRES_USER=access"
      - "POSTGRES_PASSWORD=access"
      - "POSTGRES_DB=access_task_state"
    ports:
      - "5432:5432"
    volumes:
      - taskdb-data:/var/lib/postgresql/data

  # Database to put tracking/stats/etc.
  trackdb:
    image: solr:8.4-slim
    ports:
     - "8983:8983"
    volumes:
      - ${DATA_TRACKDB}:/var/solr
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - tracking

volumes:
  taskdb-data:
