version: "3.2"

services:

  tasks:
    command: bash
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    volumes:
      - .:/host
    extra_hosts:
      - "namenode:${NAMENODE_IP}"
      - "jobtracker:${JOBTRACKER_IP}"

